fragment ListedSuggestion on Suggestion {
  ...SuggestionCore
  createdAt
  createdBy {
    id
    name
  }
  status
  thumb: image(width: 100, height: 100)
}

query listSuggestions($filter: SuggestionsFilter, $page: Page) {
  suggestions(filter: $filter, page: $page) {
    nodes {
      ...ListedSuggestion
    }
    count
  }
}
