query listSections(
  $page: Page
  $filter: SectionsFilter
  $thumbWidth: Int
  $thumbHeight: Int
) {
  sections(page: $page, filter: $filter) {
    nodes {
      ...SectionCore
      description
      shape
      region {
        id
      }
      ...SectionEnds
      ...SectionMeasurements
      ...TimestampedMeta
      ...SectionPOIs
      ...SectionTags
      ...SectionLicense
      media {
        nodes {
          ...MediaCore
          image
          thumb: image(width: $thumbWidth, height: $thumbHeight)
        }
        count
      }
    }
    count
  }
}
