projects:
  whitewater-guide:
    schemaPath: services/backend/merged-schema.graphql
    includes:
      - services/backend/merged-schema.graphql
    excludes:
      - services/backend/src/**
      - services/backend/dist/**
