version: '3'

services:
  meteor:
    build:
      dockerfile: meteor.docker
      context: .docker
    ports:
      - "3333:3000"
      - "5858:5858"
      - "5959:5959"
    volumes:
      - ./backend:/var/www/whitewater
    networks:
      - whitewater_network
    environment:
      - MONGO_URL=mongodb://mongo:27017/whitewater
    depends_on:
      - "mongo"
    command: ["dockerize", "-wait", "tcp://mongo:27017", "meteor", "debug", "--settings", "settings.development.json"]
  mongo:
    image: mongo:3.2
    networks:
      - whitewater_network
    ports:
      - "3334:27017"
networks:
  whitewater_network:
    driver: bridge