version: '3.8'

# Use docker-compose -f docker-compose.yml -f docker-compose.backend.yml up
# To test if production image works
services:
  backend:
    labels:
      guide.whitewater: ''
    container_name: ww-backend
    build:
      dockerfile: ./packages/backend/Dockerfile
      context: .
      labels:
        guide.whitewater: ''
    env_file:
      - ./packages/backend/.env
      - ./packages/backend/.env.local
    environment:
      - POSTGRES_HOST=db
      - MINIO_HOST=minio
      - GORGE_HOST=gorge
    ports:
      - '3333:3333'
