schema: packages/schema/schema/*.graphql
documents:
  - 'packages/schema/schema/*.graphql'
  - 'packages/schema/fragments/*.gql'
  - 'packages/backend/src/**/__tests__/*.ts'
  - 'packages/backend/src/**/*.test.ts'
