settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: web
  path: /go/src/workers
  args:
  - --db=inmemory
  - --cache=inmemory
  commands:
    test:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    - ../all-at-once
    - ../core
    - ../galicia
    - ../galicia2
    - ../georgia
    - ../norway
    - ../one-by-one
    - ../riverzone
    ignored_paths:
    - .git
    - .realize
    - vendor
- name: cli
  path: /go/src/cli
  commands:
    test:
      status: true
    install:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    - ../all-at-once
    - ../core
    - ../galicia
    - ../galicia2
    - ../georgia
    - ../norway
    - ../one-by-one
    - ../riverzone
    ignored_paths:
    - .git
    - .realize
    - vendor
