fragment DescentForm on Descent {
  ...DescentCore

  section {
    ...DescentSection
  }
}

query getDescent($descentId: ID, $shareToken: String) {
  descent(id: $descentId, shareToken: $shareToken) {
    ...DescentForm
  }
}
