query regionsList($coverWidth: Int) {
  regions {
    nodes {
      id
      name
      favorite
      gauges {
        count
      }
      sections {
        count
      }
      coverImage {
        mobile(width: $coverWidth)
      }
    }
    count
  }
}
