FROM node:12.14.1

ENV PROJECT_ROOT /opt/app

RUN mkdir -p /tmp/app \
 && mkdir -p /opt/app \
 && chown -R node /opt/app

RUN npm install -g chokidar-cli pm2@3.5.1

COPY package.json yarn.lock /tmp/app/

# Typescript is compiled on host, tests run on host, so it's safe to use --production here
RUN cd /tmp/app/ && yarn install --production

WORKDIR $PROJECT_ROOT

COPY bin /opt/bin

CMD ["/opt/bin/start_dev.sh"]
