fragment DescentDetails on Descent {
  ...DescentCore
  ...TimestampedMeta

  section {
    ...DescentSection
  }
}
query descentDetails($descentId: ID) {
  descent(id: $descentId) {
    ...DescentDetails
  }
}
