fragment SuggestedSection on Section {
  id
  createdAt
  createdBy {
    id
    name
  }
  region {
    id
    name
  }
  river {
    id
    name
  }
  name
}

query suggestedSections($filter: SectionsFilter, $page: Page) {
  sections(filter: $filter, page: $page) {
    nodes {
      ...SuggestedSection
    }
    count
  }
}
