mutation upsertSection($section: SectionInput!) {
  upsertSection(section: $section) {
    ...SectionCore
    shape
    description
    region {
      id
      name
    }
    ...SectionEnds
    ...SectionMeasurements
    ...SectionPOIs
    ...SectionTags
    ...SectionLicense
    ...SectionFlows
    ...TimestampedMeta
  }
}
