export enum ApolloErrorCodes {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  BAD_USER_INPUT = 'BAD_USER_INPUT',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  MUTATION_NOT_ALLOWED = 'MUTATION_NOT_ALLOWED',
}
