server_name: 'whitewater.guide'

pid_file: /data/homeserver.pid

presence:
  enabled: false

require_auth_for_profile_requests: true

default_room_version: '6'

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true

    resources:
      - names: [client]
        compress: false

federation_domain_whitelist: []
allow_profile_lookup_over_federation: false
allow_device_name_lookup_over_federation: false

database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: postgres
    password: whitewater
    database: synapse
    host: db.local
    port: 5432
    cp_min: 5
    cp_max: 10
    args:
    keepalives_idle: 10
    keepalives_interval: 10
    keepalives_count: 3

log_config: '/config/my.matrix.host.log.config'

media_store_path: '/data/media_store'

enable_registration: false

# If set, allows registration of standard or admin accounts by anyone who
# has the shared secret, even if registration is otherwise disabled.
#
registration_shared_secret: '__synapse_registration_shared_secret__'

allow_guest_access: false

auto_join_rooms:
  - '#app:whitewater.guide'

autocreate_auto_join_rooms: true

enable_metrics: true

report_stats: true

# a secret which is used to sign access tokens. If none is specified,
# the registration_shared_secret is used, if one is given; otherwise,
# a secret key is derived from the signing key.
#
macaroon_secret_key: 'pI#RbIZi05*KAUC.E0M4SPBAHSFykyoIKh;8.ao1CRlqpBASB+'

# a secret which is used to calculate HMACs for form values, to stop
# falsification of values. Must be specified for the User Consent
# forms to work.
#
form_secret: 'xS^pf6FzkdI4py&A8@NCohs~WO68b#xbK8mi2^d;Wx;C^Dbioo'

signing_key_path: '/config/my.matrix.host.signing.key'

trusted_key_servers: []

jwt_config:
  enabled: true
  secret: '__access_token_secret__'
  algorithm: 'HS256'
  subject_claim: 'id'

password_config:
  enabled: true

user_directory:
  enabled: false

stats:
  enabled: true

enable_room_list_search: true

alias_creation_rules:
  - user_id: '*'
    alias: '*'
    room_id: '*'
    action: allow

room_list_publication_rules:
  - user_id: '*'
    alias: '*'
    room_id: '*'
    action: allow
