export enum Screens {
  ROOT_STACK = 'ROOT_STACK',

  REGIONS_LIST = 'REGIONS_LIST',

  REGION_STACK = 'REGION_STACK',
  REGION_TABS = 'REGION_TABS',
  REGION_MAP = 'REGION_MAP',
  REGION_SECTIONS_LIST = 'REGION_SECTIONS_LIST',
  REGION_INFO = 'REGION_INFO',

  ADD_SECTION_SCREEN = 'ADD_SECTION_SCREEN',
  ADD_SECTION_TABS = 'ADD_SECTION_TABS',
  ADD_SECTION_MAIN = 'ADD_SECTION_MAIN',
  ADD_SECTION_ATTRIBUTES = 'ADD_SECTION_ATTRIBUTES',
  ADD_SECTION_DESCRIPTION = 'ADD_SECTION_DESCRIPTION',
  ADD_SECTION_FLOWS = 'ADD_SECTION_FLOWS',
  ADD_SECTION_PHOTOS = 'ADD_SECTION_PHOTOS',
  ADD_SECTION_RIVER = 'ADD_SECTION_RIVER',
  ADD_SECTION_GAUGE = 'ADD_SECTION_GAUGE',
  ADD_SECTION_SHAPE = 'ADD_SECTION_SHAPE',
  ADD_SECTION_PHOTO = 'ADD_SECTION_PHOTO',

  SECTION_SCREEN = 'SECTION_SCREEN',
  SECTION_MAP = 'SECTION_MAP',
  SECTION_CHART = 'SECTION_CHART',
  SECTION_INFO = 'SECTION_INFO',
  SECTION_GUIDE = 'SECTION_GUIDE',
  SECTION_MEDIA = 'SECTION_MEDIA',

  MY_PROFILE = 'MY_PROFILE',

  FILTER = 'FILTER',

  AUTH_STACK = 'AUTH_STACK',
  AUTH_MAIN = 'AUTH_MAIN',
  AUTH_SIGN_IN = 'AUTH_SIGN_IN',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_FORGOT = 'AUTH_FORGOT',
  AUTH_RESET = 'AUTH_RESET',
  AUTH_WELCOME = 'AUTH_WELCOME',

  PURCHASE_STACK = 'PURCHASE_STACK',
  PURCHASE_BUY = 'PURCHASE_BUY',
  PURCHASE_ALREADY_HAVE = 'PURCHASE_ALREADY_HAVE',
  PURCHASE_VERIFY = 'PURCHASE_VERIFY',
  PURCHASE_SUCCESS = 'PURCHASE_SUCCESS',

  LOGBOOK = 'LOGBOOK',
  DESCENT = 'DESCENT',
  DESCENT_FORM = 'DESCENT_FORM',
  DESCENT_FORM_SECTION = 'DESCENT_FORM_SECTION',
  DESCENT_FORM_DATE = 'DESCENT_FORM_DATE',
  DESCENT_FORM_LEVEL = 'DESCENT_FORM_LEVEL',
  DESCENT_FORM_COMMENT = 'DESCENT_FORM_COMMENT',

  PLAIN = 'PLAIN',

  LICENSE = 'LICENSE',

  WEB_VIEW = 'WEB_VIEW',

  SUGGESTION = 'SUGGESTION',
}
