version: '3.6'

services:
  # Node.js backend
  backend:
    ports:
      - '3333:3333'

  # Postgres sql database
  db:
    ports:
      - '5432:5432'

  # Minio to store images
  minio:
    ports:
      - '9000:9000'

  # Caddy reverse proxy
  caddy:
    ports:
      - '80:2015'

  # imageproxy to generate thumbnails
  imageproxy:

  # Redis for sessions and last measurements
  redis:
    ports:
      - '6379:6379'

  # Workers to harvest some data
  workers:

  # Serve static landing
  landing:

  # Serve static web client
  web:
