# Autofill all
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "autofill",
  "script": "canada"
}

###
# Autofill Quebec & BC
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "autofill",
  "script": "canada",
  "extras": {
    "provinces": "QC,BC"
  }
}

###
# Harvest Quebec & BC
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "harvest",
  "script": "canada",
  "extras": {
    "provinces": "QC,BC"
  }
}

###
