# Autofill all
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "autofill",
  "script": "canada"
}

###
# Autofill Quebec
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "autofill",
  "script": "canada",
  "extras": {
    "province": "QC"
  }
}

###
# Harvest Quebec
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "harvest",
  "script": "canada",
  "extras": {
    "province": "QC"
  }
}

###
