export default `Effective date: June 12, 2019

Whitewater guide app mobile application is also referred in this document to as "Service" or "app" ("us", "we", or "our").

This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our app and the choices you have associated with that data.

We use your data to provide and improve the app. By using the app, you agree to the collection and use of information in accordance with this policy. 

# Definitions

- **Personal Data** means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
- **Usage Data** is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
- **Data Controller** means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.
For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
- **Data Processor** (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
We may use the services of various Service Providers in order to process your data more effectively.
- **Data Subject** (or User) is any living individual who is using our app and is the subject of Personal Data.

# Information Collection and Use

We collect several different types of information for various purposes to provide and improve our Service to you.
Types of Data Collected

## Personal Data
While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
- Email address
- First name and last name
- Facebook account
- Usage Data

We may use your Personal Data to contact you with technical or security issues information. You may opt out of receiving any, or all, of these communications from us by contacting us.

## Usage Data
When you access the Service with a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the  language of your device and other diagnostic data ("Usage Data").

## Location Data
When you use our app, we may use GPS technology (or other similar technology) to determine and store your current location in order to adjust the map widget for you. If you do not want us to use your location for the purposes set forth above, you should turn off the location services for the mobile application located in your mobile phone settings.

# Use of Data
Whitewater guide app uses the collected data for various purposes:
- To provide and maintain our Service
- You have given us permission to do so
- To notify you about changes to our Service
- To allow you to participate in interactive features of our Service when you choose to do so
- To provide customer support
- To gather analysis or valuable information so that we can improve our Service
- To monitor the usage of our Service
- To detect, prevent and address technical issues

## Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)

If you are from the European Economic Area (EEA), whitewater.guide legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.

Whitewater guide app may process your Personal Data because:
- We need to improve the user experience such as showing the content of the app in the user's language (if the translation is available) etc.
- To process premium purchases
- To show you the position of your device on the map
- To improve the app
- To let the users add content and leave the logbooks entries
- The processing is in our legitimate interests and it is not overridden by your rights
- To comply with the law

## Data Retention Policy, Managing Your Information

We will retain User Provided data for as long as you use the Application and for a reasonable time thereafter. We will retain Automatically Collected information for the time needed and thereafter may store it in aggregate. If you’d like us to delete User Provided Data that you have provided via the Application, please contact us at [info@whitewater.guide](info@whitewater.guide) and we will respond in a reasonable time. Please note that some or all of the User Provided Data may be required in order for the Application to function properly.

## Transfer of Data
Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of EU and outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.

If you are located outside Russian Federation and choose to provide information to us, please note that we might transfer the data, including Personal Data, to Russian Federation and process it there.
Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.

Whitewater guide app will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.

## Do third parties see and/or have access to information obtained by the Application?

Yes. We will share your information with third parties only in the ways that are described in this privacy statement.

We may disclose User Provided and Automatically Collected Information:

- as required by law, such as to comply with a subpoena, or similar legal process;
- when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request;
- if we are involved in a merger, acquisition, or sale of all or a portion of our assets, you will be notified via email and/or a prominent notice in the Application of any change in ownership or uses of this information, as well as any choices you may have regarding this information.

## Security of Data

We are concerned about safeguarding the confidentiality of your information. We provide physical, electronic, and procedural safeguards to protect information we process and maintain. For example, we limit access to this information to the developer team only who need to know that information in order to operate, develop or improve our Application. Please be aware that, although we endeavor provide reasonable security for information we process and maintain, no security system can prevent all potential security breaches.

## Your Data Protection Rights under the General Data Protection Regulation (GDPR)

If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Whitewater guide app aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.
If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
**In certain circumstances, you have the following data protection rights:**
- The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.
- The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.
- The right to object. You have the right to object to our processing of your Personal Data.
- The right of restriction. You have the right to request that we restrict the processing of your personal information.
- The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.
- The right to withdraw consent. You also have the right to withdraw your consent at any time where whitewater.guide relied on your consent to process your personal information.

Please note that we may ask you to verify your identity before responding to such requests.
You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).

# Analytics
We may use third-party Service Providers to monitor and analyse the use of our Service.
Firebase
Firebase is an analytics service provided by Google Inc.
You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in [Privacy Policy](https://policies.google.com/privacy).
We also encourage you to review the Google's [policy](https://support.google.com/analytics/answer/6004245) for safeguarding your data.
For more information on what type of information Firebase collects, please visit the Google Privacy Terms web [page](https://policies.google.com/privacy).

# Payments
We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.

**The payment processors we work with are**
- Apple Store In-App Payments
Their Privacy Policy can be viewed [here](https://www.apple.com/legal/privacy/en-ww/).
- Google Play In-App Payments
Their Privacy Policy can be viewed [here](https://www.google.com/policies/privacy/).

## Links to Other Sites
Our app may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.`;
