fragment ListedRiver on River {
  id
  name
  altNames
  region {
    id
    name
  }
  sections {
    count
  }
}

query listRivers($page: Page, $filter: RiversFilter) {
  rivers(page: $page, filter: $filter) {
    nodes {
      ...ListedRiver
    }
    count
  }
}
