import Knex = require('knex');

const tags = [
  { id: 'waterfalls', category: 'kayaking' },
  { id: 'creeking', category: 'kayaking' },
  { id: 'pool_drop', category: 'kayaking' },
  { id: 'big_volume', category: 'kayaking' },
  { id: 'playboating', category: 'kayaking' },
  { id: 'boulder_garden', category: 'kayaking' },
  { id: 'multiday', category: 'kayaking' },
  { id: 'park_n_huck', category: 'kayaking' },
  { id: 'slalom', category: 'kayaking' },
  { id: 'canyon', category: 'kayaking' },
  { id: 'steep_continuous', category: 'kayaking' },
  { id: 'race_course', category: 'kayaking' },
  { id: 'bedrock', category: 'kayaking' },
  { id: 'people', category: 'hazards' },
  { id: 'man_made', category: 'hazards' },
  { id: 'fishermen', category: 'hazards' },
  { id: 'undercuts', category: 'hazards' },
  { id: 'log_jams', category: 'hazards' },
  { id: 'syphons', category: 'hazards' },
  { id: 'portage', category: 'hazards' },
  { id: 'dam', category: 'hazards' },
  { id: 'weir', category: 'hazards' },
  { id: 'Syphon_bridge', category: 'hazards' },
  { id: 'avalanches', category: 'hazards' },
  { id: 'rock_falls', category: 'hazards' },
  { id: 'must-run', category: 'hazards' },
  { id: 'artificial', category: 'supply' },
  { id: 'snowmelt', category: 'supply' },
  { id: 'groundwater', category: 'supply' },
  { id: 'rain', category: 'supply' },
  { id: 'glacier', category: 'supply' },
  { id: 'lakes', category: 'supply' },
  { id: 'race', category: 'misc' },
  { id: 'changing_rapids', category: 'misc' },
  { id: 'roadside', category: 'misc' },
  { id: 'dam_soon', category: 'misc' },
  { id: '4x4', category: 'misc' },
  { id: 'hike_in', category: 'misc' },
  { id: 'ropes_needed', category: 'misc' },
  { id: 'restricted_access', category: 'misc' },
  { id: 'hike_out', category: 'misc' },
  { id: 'gyro', category: 'misc' },
  { id: 'flats', category: 'misc' },
];

const tagsEn = [
  { tag_id: 'waterfalls', name: 'Waterfalls', language: 'en' },
  { tag_id: 'creeking', name: 'Creeking', language: 'en' },
  { tag_id: 'pool_drop', name: 'Pool-drop', language: 'en' },
  { tag_id: 'big_volume', name: 'Big volume', language: 'en' },
  { tag_id: 'playboating', name: 'Playboating', language: 'en' },
  { tag_id: 'boulder_garden', name: 'Boulder garden', language: 'en' },
  { tag_id: 'multiday', name: 'Multiday', language: 'en' },
  { tag_id: 'park_n_huck', name: 'Park and huck', language: 'en' },
  { tag_id: 'slalom', name: 'Slalom', language: 'en' },
  { tag_id: 'canyon', name: 'Canyon', language: 'en' },
  { tag_id: 'steep_continuous', name: 'Steep continuous', language: 'en' },
  { tag_id: 'race_course', name: 'Race course', language: 'en' },
  { tag_id: 'bedrock', name: 'Bedrock', language: 'en' },
  { tag_id: 'people', name: 'People', language: 'en' },
  { tag_id: 'man_made', name: 'Artificial objects', language: 'en' },
  { tag_id: 'fishermen', name: 'Fishermen', language: 'en' },
  { tag_id: 'undercuts', name: 'Undercuts', language: 'en' },
  { tag_id: 'log_jams', name: 'Log jams', language: 'en' },
  { tag_id: 'syphons', name: 'Syphons', language: 'en' },
  { tag_id: 'portage', name: 'Mandatory portage', language: 'en' },
  { tag_id: 'dam', name: 'Dam', language: 'en' },
  { tag_id: 'weir', name: 'Weir', language: 'en' },
  { tag_id: 'Syphon_bridge', name: 'Syphon bridge', language: 'en' },
  { tag_id: 'avalanches', name: 'Avalanches', language: 'en' },
  { tag_id: 'rock_falls', name: 'Rock falls', language: 'en' },
  { tag_id: 'must-run', name: 'Must-run', language: 'en' },
  { tag_id: 'artificial', name: 'Dam release', language: 'en' },
  { tag_id: 'snowmelt', name: 'Snowmelt', language: 'en' },
  { tag_id: 'groundwater', name: 'Groundwater', language: 'en' },
  { tag_id: 'rain', name: 'Rains', language: 'en' },
  { tag_id: 'glacier', name: 'Glacier', language: 'en' },
  { tag_id: 'lakes', name: 'Lakes', language: 'en' },
  { tag_id: 'race', name: 'Race', language: 'en' },
  { tag_id: 'changing_rapids', name: 'Changing rapids', language: 'en' },
  { tag_id: 'roadside', name: 'Roadside', language: 'en' },
  { tag_id: 'dam_soon', name: 'Dam soon', language: 'en' },
  { tag_id: '4x4', name: '4x4', language: 'en' },
  { tag_id: 'hike_in', name: 'Hike-in', language: 'en' },
  { tag_id: 'ropes_needed', name: 'Rope work', language: 'en' },
  { tag_id: 'restricted_access', name: 'Restricted access', language: 'en' },
  { tag_id: 'hike_out', name: 'Hike-out', language: 'en' },
  { tag_id: 'gyro', name: 'Gyro', language: 'en' },
  { tag_id: 'flats', name: 'Flat sections', language: 'en' },
];

const tagsRu = [
  { tag_id: 'waterfalls', name: 'Водопады', language: 'ru' },
  { tag_id: 'creeking', name: 'Крикинг', language: 'ru' },
  { tag_id: 'pool_drop', name: 'Пул-дроп', language: 'ru' },
  { tag_id: 'big_volume', name: 'Биг вольюм', language: 'ru' },
  { tag_id: 'playboating', name: 'Игровой сплав', language: 'ru' },
  { tag_id: 'boulder_garden', name: 'Сад камней', language: 'ru' },
  { tag_id: 'multiday', name: 'Экспедиция', language: 'ru' },
  { tag_id: 'park_n_huck', name: 'Пард энд хак', language: 'ru' },
  { tag_id: 'slalom', name: 'Слалом', language: 'ru' },
  { tag_id: 'canyon', name: 'Каньон', language: 'ru' },
  { tag_id: 'steep_continuous', name: 'Нон-стоп', language: 'ru' },
  { tag_id: 'race_course', name: 'Соревновательный участок', language: 'ru' },
  { tag_id: 'bedrock', name: 'Коренные породы', language: 'ru' },
  { tag_id: 'people', name: 'Люди', language: 'ru' },
  { tag_id: 'man_made', name: 'Техноген', language: 'ru' },
  { tag_id: 'fishermen', name: 'Рыбкаи', language: 'ru' },
  { tag_id: 'undercuts', name: 'Карманы', language: 'ru' },
  { tag_id: 'log_jams', name: 'Завалы', language: 'ru' },
  { tag_id: 'syphons', name: 'Сифоны', language: 'ru' },
  { tag_id: 'portage', name: 'Обнос', language: 'ru' },
  { tag_id: 'dam', name: 'Плотина', language: 'ru' },
  { tag_id: 'weir', name: 'Техногенный слив', language: 'ru' },
  { tag_id: 'Syphon_bridge', name: 'Сифон-мост', language: 'ru' },
  { tag_id: 'avalanches', name: 'Лавины', language: 'ru' },
  { tag_id: 'rock_falls', name: 'Камнепады', language: 'ru' },
  { tag_id: 'must-run', name: 'Маст-ран', language: 'ru' },
  { tag_id: 'artificial', name: 'Сброс плотины', language: 'ru' },
  { tag_id: 'snowmelt', name: 'Снеговое', language: 'ru' },
  { tag_id: 'groundwater', name: 'Родниковое', language: 'ru' },
  { tag_id: 'rain', name: 'Дождевое', language: 'ru' },
  { tag_id: 'glacier', name: 'Ледниковое', language: 'ru' },
  { tag_id: 'lakes', name: 'Озерное', language: 'ru' },
  { tag_id: 'race', name: 'Гонка', language: 'ru' },
  { tag_id: 'changing_rapids', name: 'Пороги перемывает', language: 'ru' },
  { tag_id: 'roadside', name: 'Вдоль дороги', language: 'ru' },
  { tag_id: 'dam_soon', name: 'Скоро заплотинят', language: 'ru' },
  { tag_id: '4x4', name: '4x4', language: 'ru' },
  { tag_id: 'hike_in', name: 'Пешая заброска', language: 'ru' },
  { tag_id: 'ropes_needed', name: 'Требуются веревки', language: 'ru' },
  { tag_id: 'restricted_access', name: 'Доступ ограничен', language: 'ru' },
  { tag_id: 'hike_out', name: 'Пешая выброска', language: 'ru' },
  { tag_id: 'gyro', name: 'Gyro', language: 'ru' },
  { tag_id: 'flats', name: 'Гладкая гребля', language: 'ru' },
];

export async function seed(db: Knex) {
  await db.table('tags').del();
  await db.table('tags_translations').del();
  await db.table('tags').insert(tags);
  await db.table('tags_translations').insert(tagsEn);
  await db.table('tags_translations').insert(tagsRu);
}
