#!/usr/bin/env bash

# These files are generated by near-operation-file and are same as generated fragments.ts
# They are generated because we want to use fragments ib backend/frontend queries
rm -rf ./packages/schema/fragments/*.ts
# Fragment on interfaces are not exported
# https://github.com/dotansimha/graphql-code-generator/issues/6090
# This is the workaround
sed -i.bak "s/type TimestampedMeta_/export type TimestampedMeta_/g" ./packages/schema/src/__generated__/fragments.ts
rm -rf ./packages/schema/src/__generated__/fragments.ts.bak
