# Autofill all
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "autofill",
  "script": "quebec"
}

###
# Harvest Quebec & BC
POST http://localhost:7080/endpoint
Cache-Control: no-cache
Content-Type: application/json

{
  "command": "harvest",
  "script": "quebec",
  "code": "011508"
}

###
